// Generated by scripts/sync-content.mjs. Do not edit by hand.
export type PublishedEntry = { id: string; slug: string; title: string; originalLanguage: string; publishedAt: string; tags: string[]; excerpt: string; body: string; };
export const publishedEntries: PublishedEntry[] = [];
