import { existsSync } from "node:fs";
import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { ensureEntriesRoot, entriesRoot, ensureOriginalIntegrity, readMetadata } from "./lib/content.mjs";

await ensureEntriesRoot();
const folders = (await readdir(entriesRoot, { withFileTypes: true })).filter((item) => item.isDirectory());
const entries = [];
function excerptFrom(body) {
  const excerpt = body.replace(/[#*_`>$]/g, "").replaceAll("[", "").replaceAll("]", "").replace(/\s+/g, " ").trim().slice(0, 210);
  return excerpt.length === 210 ? `${excerpt}…` : excerpt;
}
for (const folder of folders) {
  const metadata = await readMetadata(folder.name);
  if (metadata.status !== "published") continue;
  await ensureOriginalIntegrity(folder.name, metadata);
  const publishedPath = path.join(entriesRoot, folder.name, "published.md");
  if (!existsSync(publishedPath)) throw new Error(`Published body missing for ${folder.name}.`);
  const body = await readFile(publishedPath, "utf8");
  const originalLocale = metadata.originalLanguage;
  if (!["en", "ru"].includes(originalLocale)) throw new Error(`Unsupported original language for ${folder.name}.`);
  const versions = {
    [originalLocale]: {
      locale: originalLocale,
      slug: metadata.slug,
      title: metadata.title,
      publishedAt: metadata.publishedAt,
      tags: metadata.tags || [],
      excerpt: excerptFrom(body),
      body,
    },
  };

  for (const locale of ["en", "ru"]) {
    if (locale === originalLocale) continue;
    const translation = metadata.translations?.[locale];
    if (!translation || translation.status !== "published") continue;
    const translationPath = path.join(entriesRoot, folder.name, "translations", locale, "published.md");
    if (!existsSync(translationPath)) throw new Error(`Published ${locale} translation missing for ${folder.name}.`);
    const translatedBody = await readFile(translationPath, "utf8");
    versions[locale] = {
      locale,
      slug: translation.slug ?? metadata.slug,
      title: translation.title,
      publishedAt: translation.publishedAt,
      tags: translation.tags ?? metadata.tags ?? [],
      excerpt: excerptFrom(translatedBody),
      body: translatedBody,
    };
  }
  entries.push({
    id: metadata.id,
    originalLanguage: metadata.originalLanguage,
    versions,
  });
}
entries.sort((a, b) => {
  const aDate = Object.values(a.versions)[0].publishedAt;
  const bDate = Object.values(b.versions)[0].publishedAt;
  return Date.parse(bDate) - Date.parse(aDate);
});
const output = `// Generated by scripts/sync-content.mjs. Do not edit by hand.\nexport type Locale = "en" | "ru";\nexport type PublishedVersion = { locale: Locale; slug: string; title: string; publishedAt: string; tags: string[]; excerpt: string; body: string; };\nexport type PublishedEntry = { id: string; originalLanguage: Locale; versions: Partial<Record<Locale, PublishedVersion>>; };\nexport const publishedEntries: PublishedEntry[] = ${JSON.stringify(entries, null, 2)};\n`;
await writeFile(path.join(process.cwd(), "content", "generated.ts"), output, "utf8");
console.log(`Content synced: ${entries.length} published entr${entries.length === 1 ? "y" : "ies"}.`);
