import { existsSync } from "node:fs";
import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { ensureEntriesRoot, entriesRoot, ensureOriginalIntegrity, readMetadata } from "./lib/content.mjs";

await ensureEntriesRoot();
const folders = (await readdir(entriesRoot, { withFileTypes: true })).filter((item) => item.isDirectory());
const entries = [];
for (const folder of folders) {
  const metadata = await readMetadata(folder.name);
  if (metadata.status !== "published") continue;
  await ensureOriginalIntegrity(folder.name, metadata);
  const publishedPath = path.join(entriesRoot, folder.name, "published.md");
  if (!existsSync(publishedPath)) throw new Error(`Published body missing for ${folder.name}.`);
  const body = await readFile(publishedPath, "utf8");
  const excerpt = body.replace(/[#*_`>\[\]$]/g, "").replace(/\s+/g, " ").trim().slice(0, 210);
  entries.push({
    id: metadata.id,
    slug: metadata.slug,
    title: metadata.title,
    originalLanguage: metadata.originalLanguage,
    publishedAt: metadata.publishedAt,
    tags: metadata.tags || [],
    excerpt: excerpt.length === 210 ? `${excerpt}…` : excerpt,
    body,
  });
}
entries.sort((a, b) => Date.parse(b.publishedAt) - Date.parse(a.publishedAt));
const output = `// Generated by scripts/sync-content.mjs. Do not edit by hand.\nexport type PublishedEntry = { id: string; slug: string; title: string; originalLanguage: string; publishedAt: string; tags: string[]; excerpt: string; body: string; };\nexport const publishedEntries: PublishedEntry[] = ${JSON.stringify(entries, null, 2)};\n`;
await writeFile(path.join(process.cwd(), "content", "generated.ts"), output, "utf8");
console.log(`Content synced: ${entries.length} published entr${entries.length === 1 ? "y" : "ies"}.`);
